name: Test-And-Start

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: make setup

    - name: Test start
      run: make test

    - name: Lint start
      run: make lint

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: NPM Cache
      uses: actions/setup-node@v3
      with:
        cache: 'npm'

